produit_homepage:
    path:     /admin/products
    defaults: { _controller: ProduitBundle:Produit:afficher }
produit_ajouter:
    path:     /seller/add_pd
    defaults: { _controller: ProduitBundle:Produit:AjouterProduit }
produit_supprimer:
    path:     seller/supp_pd{id}
    defaults: { _controller: ProduitBundle:Produit:SupprimerProduit }
produit_modifier:
    path:     seller/modif_pd{id}
    defaults: { _controller: ProduitBundle:Produit:modifierProduit }
categorie_homepage:
    path:     seller/afficherCatg
    defaults: { _controller: ProduitBundle:Produit:afficherCategorie }
categorie_ajouter:
    path:     seller/ajouterCatg
    defaults: { _controller: ProduitBundle:Produit:AjouterCategorie }
categorie_supprimer:
    path:     seller/supp_catg{id}
    defaults: { _controller: ProduitBundle:Produit:SupprimerCategorie }
categorie_modifier:
    path:     seller/modif_catg{id}
    defaults: { _controller: ProduitBundle:Produit:modifierCategorie }
frontPage:
    path:     /
    defaults: { _controller: ProduitBundle:Produit:frontPage }
detailProduit:
    path:     buyer/detailProduit/{id}
    defaults: { _controller: ProduitBundle:Produit:detailProduit }
findAllProductsAndCategory:
    path:     buyer/findAllProductsAndCategory/{category}
    defaults: { _controller: ProduitBundle:Produit:findAllProductsAndCategory }
CalculateMoyenprice:
  path:     buyer/CalculateMoyenprice/{category}
  defaults: { _controller: ProduitBundle:Produit:CalculateMoyenprice }
searchbyprice:
    path:     buyer/searchbyprice
    defaults: { _controller: ProduitBundle:Produit:searchbyprice }