# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ACHETEUR:       ROLE_ACHETEUR
        ROLE_VENDEUR:       [ROLE_VENDEUR, ROLE_ACHETEUR]
        ROLE_ADMIN:       [ROLE_ADMIN, ROLE_VENDEUR, ROLE_ACHETEUR]
        ROLE_SUPER_ADMIN:       [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            logout_on_user_change : true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/seller/, role: ROLE_VENDEUR}
        - { path: ^/buyer/, role: ROLE_ACHETEUR }

