<?php

namespace SAVBundle\Repository;

/**
 * recRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recRepository extends \Doctrine\ORM\EntityRepository
{
}
