<?php

namespace SAVBundle\Repository;

/**
 * repRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class repRepository extends \Doctrine\ORM\EntityRepository
{
}
