<?php

namespace PanierBundle\Repository;

/**
 * LigneCmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCmdRepository extends \Doctrine\ORM\EntityRepository
{
}
